apiVersion: v1
kind: Namespace
metadata:
  name: gray
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gray
  namespace: gray
spec:
  hard:
    cpu: "1000"
    memory: 200Gi
    pods: "1"
---
apiVersion: v1
kind: Pod
metadata:
  name: nepetersv1-limits
  namespace: gray
spec:
  containers:
  - name: nepetersv1
    image: neilpeterson/nepetersv1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: nepetersv1-no-limits
  namespace: gray
spec:
  containers:
  - name: nepetersv1
    image: neilpeterson/nepetersv1