apiVersion: v1
kind: Pod
metadata:
  name: nepetersv1-limits-2
  namespace: gray
spec:
  containers:
  - name: nepetersv1-2
    image: neilpeterson/nepetersv1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"