apiVersion: v1
kind: Namespace
metadata:
  name: pink
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pink
  namespace: pink
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 128Mi
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: nepetersv1-no-limits
  namespace: pink
spec:
  containers:
  - name: nepetersv1
    image: neilpeterson/nepetersv1
