# kubectl taint nodes aks-nodepool1-19214297-2 dept-

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nepetersv1-consume-cpu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nepetersv1-consume-cpu
  template:
    metadata:
      labels:
        app: nepetersv1-consume-cpu
    spec:
      containers:
      - name: nepetersv1
        image: neilpeterson/nepetersv1
        resources:
          requests:
            cpu: 1
            memory: 128Mi
          limits:
            cpu: 1
            memory: 256Mi
        ports:
        - containerPort: 80
          name: http