apiVersion: v1
kind: Pod
metadata:
  name: nepetersv1-no-priority
spec:
  containers:
  - name: nepetersv1-no-priority
    image: neilpeterson/nepetersv1
    resources:
      requests:
        cpu: 1
        memory: 128Mi
      limits:
        cpu: 1
        memory: 256Mi