apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nepetersv1-node-non-sticky
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nepetersv1-node-non-sticky
    spec:
      containers:
      - name: nepetersv1-node-non-sticky
        image: neilpeterson/nepetersv1
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nepetersv1-node-sticky
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: nepetersv1-node-sticky
    spec:
      containers:
      - name: nepetersv1-node-sticky
        image: neilpeterson/nepetersv1
        ports:
        - containerPort: 80
      nodeName: aks-nodepool1-35171595-2