apiVersion: v1
kind: Namespace
metadata:
  name: lob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: lob
  name: lob
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: lob
 namespace: lob
roleRef:
 kind: Role
 name: lob
 apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: 97954f52-5561-4439-a245-2afb35b73a80
